package test.model;

import java.util.Date;

public class FileIndex {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_index.file_index_id
     *
     * @mbggenerated
     */
    private Long fileIndexId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_index.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_index.p_file_index_id
     *
     * @mbggenerated
     */
    private Long pFileIndexId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_index.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_index.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_index.parent_id
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_index.is_file
     *
     * @mbggenerated
     */
    private String isFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_index.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_index.delete_flag
     *
     * @mbggenerated
     */
    private String deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_index.file_index_id
     *
     * @return the value of file_index.file_index_id
     *
     * @mbggenerated
     */
    public Long getFileIndexId() {
        return fileIndexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_index.file_index_id
     *
     * @param fileIndexId the value for file_index.file_index_id
     *
     * @mbggenerated
     */
    public void setFileIndexId(Long fileIndexId) {
        this.fileIndexId = fileIndexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_index.user_id
     *
     * @return the value of file_index.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_index.user_id
     *
     * @param userId the value for file_index.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_index.p_file_index_id
     *
     * @return the value of file_index.p_file_index_id
     *
     * @mbggenerated
     */
    public Long getpFileIndexId() {
        return pFileIndexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_index.p_file_index_id
     *
     * @param pFileIndexId the value for file_index.p_file_index_id
     *
     * @mbggenerated
     */
    public void setpFileIndexId(Long pFileIndexId) {
        this.pFileIndexId = pFileIndexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_index.name
     *
     * @return the value of file_index.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_index.name
     *
     * @param name the value for file_index.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_index.path
     *
     * @return the value of file_index.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_index.path
     *
     * @param path the value for file_index.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_index.parent_id
     *
     * @return the value of file_index.parent_id
     *
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_index.parent_id
     *
     * @param parentId the value for file_index.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_index.is_file
     *
     * @return the value of file_index.is_file
     *
     * @mbggenerated
     */
    public String getIsFile() {
        return isFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_index.is_file
     *
     * @param isFile the value for file_index.is_file
     *
     * @mbggenerated
     */
    public void setIsFile(String isFile) {
        this.isFile = isFile == null ? null : isFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_index.create_time
     *
     * @return the value of file_index.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_index.create_time
     *
     * @param createTime the value for file_index.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_index.delete_flag
     *
     * @return the value of file_index.delete_flag
     *
     * @mbggenerated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_index.delete_flag
     *
     * @param deleteFlag the value for file_index.delete_flag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }
}