package test.model;

import java.util.Date;

public class FriendRelationship {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_relationship.friend_relationship_id
     *
     * @mbggenerated
     */
    private Long friendRelationshipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_relationship.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_relationship.friend_user_id
     *
     * @mbggenerated
     */
    private Long friendUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_relationship.begin_time
     *
     * @mbggenerated
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_relationship.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_relationship.friend_relationship_id
     *
     * @return the value of friend_relationship.friend_relationship_id
     *
     * @mbggenerated
     */
    public Long getFriendRelationshipId() {
        return friendRelationshipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_relationship.friend_relationship_id
     *
     * @param friendRelationshipId the value for friend_relationship.friend_relationship_id
     *
     * @mbggenerated
     */
    public void setFriendRelationshipId(Long friendRelationshipId) {
        this.friendRelationshipId = friendRelationshipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_relationship.user_id
     *
     * @return the value of friend_relationship.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_relationship.user_id
     *
     * @param userId the value for friend_relationship.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_relationship.friend_user_id
     *
     * @return the value of friend_relationship.friend_user_id
     *
     * @mbggenerated
     */
    public Long getFriendUserId() {
        return friendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_relationship.friend_user_id
     *
     * @param friendUserId the value for friend_relationship.friend_user_id
     *
     * @mbggenerated
     */
    public void setFriendUserId(Long friendUserId) {
        this.friendUserId = friendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_relationship.begin_time
     *
     * @return the value of friend_relationship.begin_time
     *
     * @mbggenerated
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_relationship.begin_time
     *
     * @param beginTime the value for friend_relationship.begin_time
     *
     * @mbggenerated
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_relationship.end_time
     *
     * @return the value of friend_relationship.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_relationship.end_time
     *
     * @param endTime the value for friend_relationship.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}