package test.model;

import java.util.Date;

public class PFileIndex {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_file_index.p_file_index_id
     *
     * @mbggenerated
     */
    private Long pFileIndexId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_file_index.p_name
     *
     * @mbggenerated
     */
    private String pName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_file_index.p_path
     *
     * @mbggenerated
     */
    private String pPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_file_index.file_size
     *
     * @mbggenerated
     */
    private Long fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_file_index.file_md5
     *
     * @mbggenerated
     */
    private String fileMd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_file_index.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_file_index.p_file_index_id
     *
     * @return the value of p_file_index.p_file_index_id
     *
     * @mbggenerated
     */
    public Long getpFileIndexId() {
        return pFileIndexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_file_index.p_file_index_id
     *
     * @param pFileIndexId the value for p_file_index.p_file_index_id
     *
     * @mbggenerated
     */
    public void setpFileIndexId(Long pFileIndexId) {
        this.pFileIndexId = pFileIndexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_file_index.p_name
     *
     * @return the value of p_file_index.p_name
     *
     * @mbggenerated
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_file_index.p_name
     *
     * @param pName the value for p_file_index.p_name
     *
     * @mbggenerated
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_file_index.p_path
     *
     * @return the value of p_file_index.p_path
     *
     * @mbggenerated
     */
    public String getpPath() {
        return pPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_file_index.p_path
     *
     * @param pPath the value for p_file_index.p_path
     *
     * @mbggenerated
     */
    public void setpPath(String pPath) {
        this.pPath = pPath == null ? null : pPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_file_index.file_size
     *
     * @return the value of p_file_index.file_size
     *
     * @mbggenerated
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_file_index.file_size
     *
     * @param fileSize the value for p_file_index.file_size
     *
     * @mbggenerated
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_file_index.file_md5
     *
     * @return the value of p_file_index.file_md5
     *
     * @mbggenerated
     */
    public String getFileMd5() {
        return fileMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_file_index.file_md5
     *
     * @param fileMd5 the value for p_file_index.file_md5
     *
     * @mbggenerated
     */
    public void setFileMd5(String fileMd5) {
        this.fileMd5 = fileMd5 == null ? null : fileMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_file_index.create_time
     *
     * @return the value of p_file_index.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_file_index.create_time
     *
     * @param createTime the value for p_file_index.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}