package test.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ShareFileExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table share_file
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table share_file
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table share_file
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_file
     *
     * @mbggenerated
     */
    public ShareFileExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_file
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_file
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_file
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_file
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_file
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_file
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_file
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_file
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_file
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_file
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table share_file
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andShareFileIdIsNull() {
            addCriterion("share_file_id is null");
            return (Criteria) this;
        }

        public Criteria andShareFileIdIsNotNull() {
            addCriterion("share_file_id is not null");
            return (Criteria) this;
        }

        public Criteria andShareFileIdEqualTo(Long value) {
            addCriterion("share_file_id =", value, "shareFileId");
            return (Criteria) this;
        }

        public Criteria andShareFileIdNotEqualTo(Long value) {
            addCriterion("share_file_id <>", value, "shareFileId");
            return (Criteria) this;
        }

        public Criteria andShareFileIdGreaterThan(Long value) {
            addCriterion("share_file_id >", value, "shareFileId");
            return (Criteria) this;
        }

        public Criteria andShareFileIdGreaterThanOrEqualTo(Long value) {
            addCriterion("share_file_id >=", value, "shareFileId");
            return (Criteria) this;
        }

        public Criteria andShareFileIdLessThan(Long value) {
            addCriterion("share_file_id <", value, "shareFileId");
            return (Criteria) this;
        }

        public Criteria andShareFileIdLessThanOrEqualTo(Long value) {
            addCriterion("share_file_id <=", value, "shareFileId");
            return (Criteria) this;
        }

        public Criteria andShareFileIdIn(List<Long> values) {
            addCriterion("share_file_id in", values, "shareFileId");
            return (Criteria) this;
        }

        public Criteria andShareFileIdNotIn(List<Long> values) {
            addCriterion("share_file_id not in", values, "shareFileId");
            return (Criteria) this;
        }

        public Criteria andShareFileIdBetween(Long value1, Long value2) {
            addCriterion("share_file_id between", value1, value2, "shareFileId");
            return (Criteria) this;
        }

        public Criteria andShareFileIdNotBetween(Long value1, Long value2) {
            addCriterion("share_file_id not between", value1, value2, "shareFileId");
            return (Criteria) this;
        }

        public Criteria andShareUserIdIsNull() {
            addCriterion("share_user_id is null");
            return (Criteria) this;
        }

        public Criteria andShareUserIdIsNotNull() {
            addCriterion("share_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andShareUserIdEqualTo(Long value) {
            addCriterion("share_user_id =", value, "shareUserId");
            return (Criteria) this;
        }

        public Criteria andShareUserIdNotEqualTo(Long value) {
            addCriterion("share_user_id <>", value, "shareUserId");
            return (Criteria) this;
        }

        public Criteria andShareUserIdGreaterThan(Long value) {
            addCriterion("share_user_id >", value, "shareUserId");
            return (Criteria) this;
        }

        public Criteria andShareUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("share_user_id >=", value, "shareUserId");
            return (Criteria) this;
        }

        public Criteria andShareUserIdLessThan(Long value) {
            addCriterion("share_user_id <", value, "shareUserId");
            return (Criteria) this;
        }

        public Criteria andShareUserIdLessThanOrEqualTo(Long value) {
            addCriterion("share_user_id <=", value, "shareUserId");
            return (Criteria) this;
        }

        public Criteria andShareUserIdIn(List<Long> values) {
            addCriterion("share_user_id in", values, "shareUserId");
            return (Criteria) this;
        }

        public Criteria andShareUserIdNotIn(List<Long> values) {
            addCriterion("share_user_id not in", values, "shareUserId");
            return (Criteria) this;
        }

        public Criteria andShareUserIdBetween(Long value1, Long value2) {
            addCriterion("share_user_id between", value1, value2, "shareUserId");
            return (Criteria) this;
        }

        public Criteria andShareUserIdNotBetween(Long value1, Long value2) {
            addCriterion("share_user_id not between", value1, value2, "shareUserId");
            return (Criteria) this;
        }

        public Criteria andAcceptUserIdIsNull() {
            addCriterion("accept_user_id is null");
            return (Criteria) this;
        }

        public Criteria andAcceptUserIdIsNotNull() {
            addCriterion("accept_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andAcceptUserIdEqualTo(Long value) {
            addCriterion("accept_user_id =", value, "acceptUserId");
            return (Criteria) this;
        }

        public Criteria andAcceptUserIdNotEqualTo(Long value) {
            addCriterion("accept_user_id <>", value, "acceptUserId");
            return (Criteria) this;
        }

        public Criteria andAcceptUserIdGreaterThan(Long value) {
            addCriterion("accept_user_id >", value, "acceptUserId");
            return (Criteria) this;
        }

        public Criteria andAcceptUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("accept_user_id >=", value, "acceptUserId");
            return (Criteria) this;
        }

        public Criteria andAcceptUserIdLessThan(Long value) {
            addCriterion("accept_user_id <", value, "acceptUserId");
            return (Criteria) this;
        }

        public Criteria andAcceptUserIdLessThanOrEqualTo(Long value) {
            addCriterion("accept_user_id <=", value, "acceptUserId");
            return (Criteria) this;
        }

        public Criteria andAcceptUserIdIn(List<Long> values) {
            addCriterion("accept_user_id in", values, "acceptUserId");
            return (Criteria) this;
        }

        public Criteria andAcceptUserIdNotIn(List<Long> values) {
            addCriterion("accept_user_id not in", values, "acceptUserId");
            return (Criteria) this;
        }

        public Criteria andAcceptUserIdBetween(Long value1, Long value2) {
            addCriterion("accept_user_id between", value1, value2, "acceptUserId");
            return (Criteria) this;
        }

        public Criteria andAcceptUserIdNotBetween(Long value1, Long value2) {
            addCriterion("accept_user_id not between", value1, value2, "acceptUserId");
            return (Criteria) this;
        }

        public Criteria andShareFiIdIsNull() {
            addCriterion("share_fi_id is null");
            return (Criteria) this;
        }

        public Criteria andShareFiIdIsNotNull() {
            addCriterion("share_fi_id is not null");
            return (Criteria) this;
        }

        public Criteria andShareFiIdEqualTo(Long value) {
            addCriterion("share_fi_id =", value, "shareFiId");
            return (Criteria) this;
        }

        public Criteria andShareFiIdNotEqualTo(Long value) {
            addCriterion("share_fi_id <>", value, "shareFiId");
            return (Criteria) this;
        }

        public Criteria andShareFiIdGreaterThan(Long value) {
            addCriterion("share_fi_id >", value, "shareFiId");
            return (Criteria) this;
        }

        public Criteria andShareFiIdGreaterThanOrEqualTo(Long value) {
            addCriterion("share_fi_id >=", value, "shareFiId");
            return (Criteria) this;
        }

        public Criteria andShareFiIdLessThan(Long value) {
            addCriterion("share_fi_id <", value, "shareFiId");
            return (Criteria) this;
        }

        public Criteria andShareFiIdLessThanOrEqualTo(Long value) {
            addCriterion("share_fi_id <=", value, "shareFiId");
            return (Criteria) this;
        }

        public Criteria andShareFiIdIn(List<Long> values) {
            addCriterion("share_fi_id in", values, "shareFiId");
            return (Criteria) this;
        }

        public Criteria andShareFiIdNotIn(List<Long> values) {
            addCriterion("share_fi_id not in", values, "shareFiId");
            return (Criteria) this;
        }

        public Criteria andShareFiIdBetween(Long value1, Long value2) {
            addCriterion("share_fi_id between", value1, value2, "shareFiId");
            return (Criteria) this;
        }

        public Criteria andShareFiIdNotBetween(Long value1, Long value2) {
            addCriterion("share_fi_id not between", value1, value2, "shareFiId");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table share_file
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table share_file
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}