package test.model;

import java.util.Date;

public class ShareFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_file.share_file_id
     *
     * @mbggenerated
     */
    private Long shareFileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_file.share_user_id
     *
     * @mbggenerated
     */
    private Long shareUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_file.accept_user_id
     *
     * @mbggenerated
     */
    private Long acceptUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_file.share_fi_id
     *
     * @mbggenerated
     */
    private Long shareFiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_file.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_file.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_file.share_file_id
     *
     * @return the value of share_file.share_file_id
     *
     * @mbggenerated
     */
    public Long getShareFileId() {
        return shareFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_file.share_file_id
     *
     * @param shareFileId the value for share_file.share_file_id
     *
     * @mbggenerated
     */
    public void setShareFileId(Long shareFileId) {
        this.shareFileId = shareFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_file.share_user_id
     *
     * @return the value of share_file.share_user_id
     *
     * @mbggenerated
     */
    public Long getShareUserId() {
        return shareUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_file.share_user_id
     *
     * @param shareUserId the value for share_file.share_user_id
     *
     * @mbggenerated
     */
    public void setShareUserId(Long shareUserId) {
        this.shareUserId = shareUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_file.accept_user_id
     *
     * @return the value of share_file.accept_user_id
     *
     * @mbggenerated
     */
    public Long getAcceptUserId() {
        return acceptUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_file.accept_user_id
     *
     * @param acceptUserId the value for share_file.accept_user_id
     *
     * @mbggenerated
     */
    public void setAcceptUserId(Long acceptUserId) {
        this.acceptUserId = acceptUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_file.share_fi_id
     *
     * @return the value of share_file.share_fi_id
     *
     * @mbggenerated
     */
    public Long getShareFiId() {
        return shareFiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_file.share_fi_id
     *
     * @param shareFiId the value for share_file.share_fi_id
     *
     * @mbggenerated
     */
    public void setShareFiId(Long shareFiId) {
        this.shareFiId = shareFiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_file.start_time
     *
     * @return the value of share_file.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_file.start_time
     *
     * @param startTime the value for share_file.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_file.end_time
     *
     * @return the value of share_file.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_file.end_time
     *
     * @param endTime the value for share_file.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}