package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.FileIndex;
import test.model.FileIndexExample;

public interface FileIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_index
     *
     * @mbggenerated
     */
    int countByExample(FileIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_index
     *
     * @mbggenerated
     */
    int deleteByExample(FileIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_index
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long fileIndexId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_index
     *
     * @mbggenerated
     */
    int insert(FileIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_index
     *
     * @mbggenerated
     */
    int insertSelective(FileIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_index
     *
     * @mbggenerated
     */
    List<FileIndex> selectByExample(FileIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_index
     *
     * @mbggenerated
     */
    FileIndex selectByPrimaryKey(Long fileIndexId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_index
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FileIndex record, @Param("example") FileIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_index
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FileIndex record, @Param("example") FileIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FileIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FileIndex record);
}