package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.PFileIndex;
import test.model.PFileIndexExample;

public interface PFileIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_file_index
     *
     * @mbggenerated
     */
    int countByExample(PFileIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_file_index
     *
     * @mbggenerated
     */
    int deleteByExample(PFileIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_file_index
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long pFileIndexId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_file_index
     *
     * @mbggenerated
     */
    int insert(PFileIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_file_index
     *
     * @mbggenerated
     */
    int insertSelective(PFileIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_file_index
     *
     * @mbggenerated
     */
    List<PFileIndex> selectByExample(PFileIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_file_index
     *
     * @mbggenerated
     */
    PFileIndex selectByPrimaryKey(Long pFileIndexId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_file_index
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PFileIndex record, @Param("example") PFileIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_file_index
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PFileIndex record, @Param("example") PFileIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_file_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PFileIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_file_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PFileIndex record);
}