package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.ShareFile;
import test.model.ShareFileExample;

public interface ShareFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_file
     *
     * @mbggenerated
     */
    int countByExample(ShareFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_file
     *
     * @mbggenerated
     */
    int deleteByExample(ShareFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_file
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long shareFileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_file
     *
     * @mbggenerated
     */
    int insert(ShareFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_file
     *
     * @mbggenerated
     */
    int insertSelective(ShareFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_file
     *
     * @mbggenerated
     */
    List<ShareFile> selectByExample(ShareFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_file
     *
     * @mbggenerated
     */
    ShareFile selectByPrimaryKey(Long shareFileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_file
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ShareFile record, @Param("example") ShareFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_file
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ShareFile record, @Param("example") ShareFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShareFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShareFile record);
}